sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
install:
  - yarn install
script:
  - yarn lint 
  - yarn test 
after_success:
  - yarn coverage 
  - yarn release
